Filling output_field on constructor raises back a TypeError, about too many arguments in this case
This reverts commit 119f360b880f04b75e5a45b21eb25c9cb24198be.